# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: duwenji
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: near-by-connect
# "service" is the name of this project. This will also be added to your AWS resource names.
service: frontend

provider:
  name: aws
  runtime: nodejs20.x
  profile: default
  region: ap-northeast-1

plugins:
  - serverless-finch

custom:
  backetName: near-by-connect-frontend-packet
  client:
      bucketName: ${self:custom.backetName}
      distributionFolder: build
      indexDocument: index.html
      errorDocument: index.html

resources:
  Resources:
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.backetName}
    S3AccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.backetName}/*
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt FrontendBucket.DomainName
              Id: ReactAppOrigin
              S3OriginConfig:
                OriginAccessIdentity: ''
          Enabled: true
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            TargetOriginId: ReactAppOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
          Comment: CloudFront distribution for Near By Connect Frontend
          PriceClass: PriceClass_All
