org: duwenji
app: near-by-connect
service: backend-service
stages:
  prod:
    observability: true
  dev:
    observability: false

provider:
  name: aws
  runtime: python3.12
  profile: default
  region: ap-northeast-1
  memorySize: 128
  timeout: 15
  tracing:
    apiGateway: true
    lambda: true        
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "DynamoDB:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "*"

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-secrets-plugin

package:
  #individually: true
  exclude:
    - node_modules/**
    - package-lock.json
    - package.json
    - README.md
    - requirements.txt
    - __pycache__/**
    - .pytest_cache/**  
    - secrets.*.yml

custom:
  stage: ${opt:stage, 'dev'}
  pythonRequirements:
    layer: true
    dockerizePip: true
  secrets: ${file(secrets.${self:custom.stage}.yml)}

functions:
  getItem:
    handler: lamda/handler.get_item
    memorySize: 128
    timeout: 15
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: item/{id}
          method: get
  createItem:
    handler: lamda/handler.create_item
    memorySize: 128
    timeout: 15
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: item
          method: post
  searchByLocation:
    handler: lamda/handler.search_by_location
    memorySize: 128
    timeout: 15
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: search
          method: get
          request:
            parameters:
              querystrings:
                longitude: true
                latitude: true                
  generateMessage:
    handler: lamda/handler.generate_message
    memorySize: 128
    timeout: 15
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: generate-message
          method: post

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: Messages
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
          - AttributeName: longitude
            AttributeType: N
          - AttributeName: latitude
            AttributeType: N
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: LocationIndex
            KeySchema:
              - AttributeName: longitude
                KeyType: HASH
              - AttributeName: latitude
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    NearByConnectKeysSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: near_by_connect_keys
        Description: "Secrets for Near By Connect application"
        SecretString: '{"openai_api_key":"${self:custom.secrets.OPENAI_API_KEY}"}'